### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by maelle**
As suggested by @bcheggeseth

### CODE REVIEW

**Comment by maelle** [comment]
It also seems https://github.com/andrie/mailmerge/blob/86dc0c0a82f7d45c0766f03e3d2f71cf4ceeedd4/R/mail_merge.R#L84 should be ` if(!preview && confirm)` I think?

I was also wondering whether the default value of confirm should be `rlang::is_interactive()`.

Lastly, I think it'd make sense to add a test that'd have caught the bug (i.e. with confirmation, and send equal to e.g. draft). If not with stubbing I can recommend https://books.ropensci.org/http-testing/ :grin: 

Thanks again for your work on this useful package @andrie! (and thanks @bcheggeseth for the bug fix).

**Comment by andrie** [comment]
> should be ` if(!preview && confirm)` I think?
> I was also wondering whether the default value of confirm should be `rlang::is_interactive()`.

No, I think the current logic is correct, since `confirm` is defined as :
> If `FALSE` asks for confirmation before sending.

Also, I don't think the default should depend on interactivity.  IMO it's safer when using this in production (i.e. non-interactively) to fail if `confirm == FALSE`.

**Comment by andrie** [comment]
> Lastly, I think it'd make sense to add a test that'd have caught the bug (i.e. with confirmation, and send equal to e.g. draft). If not with stubbing I can recommend https://books.ropensci.org/http-testing/ 😁

Yes, this makes sense.  If I can add a test in less than 30 minutes I'll add it to the package, otherwise leave this part for a future date.

**Comment by andrie** [comment]
Thank you :-)

**Comment by andrie** [comment]
I've submitted a new version to CRAN.

Also note that the new default branch is `main` (renamed from `master`)

**Pull request merged**
